###
GET http://localhost:8080/api-v1

###
POST http://localhost:8080/api-v1/users
Content-Type: application/json

{"email":"reyesdiego@hotmail.com"}

###
POST http://localhost:8080/api-v1/auth/login
Content-Type: application/json

{"email":"reyesdiego@hotmail.com", "password":"1234"}


###
POST http://localhost:8080/api-v1/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGM3NmU0ZDEyNTNhNzEwOTQ5ZmNjNjYiLCJlbWFpbCI6InJleWVzZGllZ29AaG90bWFpbC5jb20iLCJpYXQiOjE1NzM0MTc1Mjd9.kO7ZSgUxph47LvBgNe17OqD3w5GAq1zg1R4bryiLa9I

{"title":"Test Title ", "body":"Test Body @Diego"}

###
GET http://localhost:8080/api-v1/posts?tags=@Diego,@Luis
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGM2NDQ4MDY3ZmViMWQyNTlmMGMyMTMiLCJlbWFpbCI6InJleWVzZGllZ29AaG90bWFpbC5jb20iLCJpYXQiOjE1NzMzNDczMDd9.AjnhEcUkovPoqVYfka9cnqjXnRZRc7lt8MXCC_AU0nk

###
PATCH http://localhost:8080/api-v1/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJleWVzZGllZ29AaG90bWFpbC5jb20iLCJpYXQiOjE1NzMwOTY3ODF9.ShwszgBKy0ivAjSYWHTjQaW2N0lGqsUAABvR4GfsYQk

{
    "_id": "5dc3911208cc0b2d7c0cc42b",
    "title": "Test Title changed 33",
    "body": "Test Body @Diego changed 33"
}

###
DELETE http://localhost:8080/api-v1/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJleWVzZGllZ29AaG90bWFpbC5jb20iLCJpYXQiOjE1NzMwOTY3ODF9.ShwszgBKy0ivAjSYWHTjQaW2N0lGqsUAABvR4GfsYQk

{
    "_id": "5dc3911208cc0b2d7c0cc42b"
}