###
GET http://localhost:8080/api-v1

###
POST http://localhost:8080/api-v1/users
Content-Type: application/json

{"email":"reyesdiego@hotmail.com"}

###
POST http://localhost:8080/api-v1/posts
Content-Type: application/json

{"title":"Test Title ", "body":"Test Body @Diego", "userId":"5dc2fccad8f2c810a5f0b2e3"}

###
GET http://localhost:8080/api-v1/posts?tags=@Diego,@Luis

###
PATCH http://localhost:8080/api-v1/posts
Content-Type: application/json

{
    "_id": "5dc2fefd497e0b1178d94e8b",
    "title": "Test Title changed 1",
    "body": "Test Body @Diego changed 1"
  }